class ICalExportService {
  /**
   * Generates standard RFC 5545 iCalendar format string for calendar subscription
   */
  generateICalendarFeed(studyEvents = []) {
    const formatDate = (d) => {
      const date = new Date(d);
      return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    let ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//OpenPrep AI//Study Planner Sync 1.0//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:OpenPrep AI Study Schedule',
    ];

    studyEvents.forEach((ev, idx) => {
      const start = formatDate(ev.startTime || Date.now());
      const end = formatDate(ev.endTime || Date.now() + 3600000);
      const uid = `openprep-${ev.id || idx}-${Date.now()}@openprep.ai`;

      ics.push(
        'BEGIN:VEVENT',
        `UID:${uid}`,
        `DTSTAMP:${formatDate(Date.now())}`,
        `DTSTART:${start}`,
        `DTEND:${end}`,
        `SUMMARY:📚 ${ev.title || 'OpenPrep Study Session'}`,
        `DESCRIPTION:${ev.description || 'Generated by OpenPrep AI'}`,
        'STATUS:CONFIRMED',
        'END:VEVENT'
      );
    });

    ics.push('END:VCALENDAR');
    return ics.join('\r\n');
  }
}

module.exports = new ICalExportService();
