const { google } = require('googleapis');

class IntegrationService {
  constructor() {
    this.oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID || 'mock-client-id',
      process.env.GOOGLE_CLIENT_SECRET || 'mock-client-secret',
      process.env.GOOGLE_REDIRECT_URI || 'http://localhost:5000/api/integrations/google/callback'
    );
  }

  /**
   * Generates authorization URL for Google Calendar scope
   */
  getGoogleAuthUrl(state = '') {
    const scopes = [
      'https://www.googleapis.com/auth/calendar.events',
      'https://www.googleapis.com/auth/calendar.readonly',
    ];

    return this.oauth2Client.generateAuthUrl({
      access_type: 'offline',
      prompt: 'consent',
      scope: scopes,
      state,
    });
  }

  /**
   * Exchanges authorization code for access and refresh tokens
   */
  async exchangeCodeForTokens(code) {
    const { tokens } = await this.oauth2Client.getToken(code);
    return tokens;
  }

  /**
   * Syncs study plan sessions to user primary Google Calendar
   */
  async syncToGoogleCalendar(tokens, studyEvents = []) {
    this.oauth2Client.setCredentials(tokens);
    const calendar = google.calendar({ version: 'v3', auth: this.oauth2Client });

    const createdEvents = [];

    for (const session of studyEvents) {
      const startDateTime = new Date(session.startTime || Date.now()).toISOString();
      const endDateTime = new Date(session.endTime || Date.now() + 3600000).toISOString();

      const eventPayload = {
        summary: `📚 OpenPrep: ${session.title || 'Focus Study Session'}`,
        description: `${session.description || 'Dedicated study block generated by OpenPrep AI.'}\n\nTopics: ${session.topics?.join(', ') || 'General'}`,
        start: { dateTime: startDateTime },
        end: { dateTime: endDateTime },
        reminders: {
          useDefault: false,
          overrides: [
            { method: 'popup', minutes: 15 },
            { method: 'email', minutes: 60 },
          ],
        },
      };

      const res = await calendar.events.insert({
        calendarId: 'primary',
        resource: eventPayload,
      });

      createdEvents.push(res.data);
    }

    return {
      syncedCount: createdEvents.length,
      events: createdEvents,
    };
  }
}

module.exports = new IntegrationService();
