/**
 * @fileoverview Document Layout & PDF Generation Engine.
 * Uses PDFKit to construct print-optimized A4 booklets with watermarks and TOC.
 */
const PDFDocument = require('pdfkit');

/**
 * Generates a printable A4 study guide PDF stream.
 * @param {Object} options - Configuration for the PDF generation.
 * @param {string} options.title - Title of the study guide.
 * @param {string} options.studentName - Name for the cover page.
 * @param {string} options.watermark - Optional watermark text.
 * @param {Array} options.sections - Array of sections (e.g., flashcards, notes).
 * @returns {Promise<Buffer>} The generated PDF buffer.
 */
async function generateStudyGuidePDF(options) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margin: 50,
                info: { Title: options.title, Author: options.studentName || 'OpenPrep AI' }
            });

            const chunks = [];
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // 1. Cover Page
            doc.fontSize(24).font('Helvetica-Bold').text(options.title, { align: 'center' });
            doc.moveDown(2);
            if (options.studentName) {
                doc.fontSize(16).font('Helvetica').text(`Prepared for: ${options.studentName}`, { align: 'center' });
            }
            doc.fontSize(12).text(`Generated by OpenPrep AI on ${new Date().toLocaleDateString()}`, { align: 'center' });
            doc.addPage();

            // 2. Table of Contents
            doc.fontSize(18).font('Helvetica-Bold').text('Table of Contents', { underline: true });
            doc.moveDown(1);
            let tocY = doc.y;
            options.sections.forEach((section, index) => {
                doc.fontSize(12).font('Helvetica').text(`${index + 1}. ${section.title}`, 50, tocY);
                // Mock page number (in real implementation, track doc.page)
                doc.text(`${index + 2}`, 500, tocY, { align: 'right' });
                tocY += 20;
            });
            doc.addPage();

            // 3. Content Sections
            options.sections.forEach(section => {
                // Watermark logic
                if (options.watermark) {
                    doc.save();
                    doc.opacity(0.1);
                    doc.fontSize(40).font('Helvetica-Bold').text(options.watermark, {
                        align: 'center',
                        width: doc.page.width,
                        angle: 45
                    });
                    doc.restore();
                }

                doc.fontSize(18).font('Helvetica-Bold').text(section.title, { underline: true });
                doc.moveDown(1);

                if (section.type === 'notes') {
                    doc.fontSize(11).font('Helvetica').text(section.content, { align: 'justify', lineGap: 4 });
                } else if (section.type === 'flashcards') {
                    section.items.forEach((item, idx) => {
                        doc.fontSize(12).font('Helvetica-Bold').text(`Q${idx + 1}: ${item.front}`);
                        doc.fontSize(11).font('Helvetica').text(`A: ${item.back}`, { indent: 20, lineGap: 2 });
                        doc.moveDown(0.5);
                    });
                } else if (section.type === 'formulas') {
                    doc.fontSize(11).font('Helvetica').text(section.content, { align: 'left', lineGap: 4 });
                }

                doc.addPage();
            });

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

module.exports = {
    generateStudyGuidePDF,
};
