const { Op } = require('sequelize');
const cron = require('node-cron');
const PDFDocument = require('pdfkit');
const User = require('../models/User');
const Progress = require('../models/Progress');
const Topic = require('../models/Topic');
const Subject = require('../models/Subject');
const ActivityLog = require('../models/ActivityLog');
const sendEmail = require('./emailService');

// Helper to generate the weekly PDF buffer using pdfkit
const generateWeeklyPDFBuffer = async (user, stats) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Title
      doc.fillColor('#1a365d').fontSize(22).font('Helvetica-Bold').text('OpenPrep AI - Weekly Mastery Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fillColor('#4a5568').fontSize(11).font('Helvetica').text(`Student Name: ${user.name || 'Scholar'}`, { align: 'center' });
      doc.text(`Report Period: Last 7 Days (Ending ${new Date().toLocaleDateString()})`, { align: 'center' });
      doc.moveDown(1.5);

      // Section 1: Weekly Progress Summary
      doc.fillColor('#2b6cb0').fontSize(14).font('Helvetica-Bold').text('Weekly Performance Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fillColor('#2d3748').fontSize(10).font('Helvetica');
      doc.text(`• Study Hours Logged This Week: ${stats.weeklyHours.toFixed(1)} hours`);
      doc.text(`• Topics Completed This Week: ${stats.completedTopicsCount}`);
      doc.text(`• Current Study Streak: ${user.streakCount || 0} days`);
      doc.moveDown(1.5);

      // Section 2: Subject-wise Breakdown Table
      doc.fillColor('#2b6cb0').fontSize(14).font('Helvetica-Bold').text('Subject Mastery Status', { underline: true });
      doc.moveDown(0.6);

      // Header row
      doc.fontSize(9).font('Helvetica-Bold').fillColor('#1a202c');
      const startY = doc.y;
      doc.text('Subject Name', 50, startY, { width: 200 });
      doc.text('Topics Count', 250, startY, { width: 100 });
      doc.text('Weekly Study Hours', 350, startY, { width: 120 });
      doc.moveDown(0.4);

      doc.font('Helvetica').fontSize(9).fillColor('#4a5568');
      if (stats.subjectStats.length === 0) {
        doc.text('No study hours recorded on any subject this week.');
      } else {
        for (const s of stats.subjectStats) {
          const currentY = doc.y;
          doc.text(s.name, 50, currentY, { width: 200 });
          doc.text(`${s.topicsCount}`, 250, currentY, { width: 100 });
          doc.text(`${s.hours.toFixed(1)}h`, 350, currentY, { width: 120 });
          doc.moveDown(0.3);
        }
      }
      doc.moveDown(1.5);

      // Section 3: Weakness Analytics
      doc.fillColor('#e53e3e').fontSize(14).font('Helvetica-Bold').text('Areas Requiring Focus (Weak Topics)', { underline: true });
      doc.moveDown(0.5);
      doc.fillColor('#2d3748').fontSize(10).font('Helvetica');
      if (stats.weakTopics.length === 0) {
        doc.text('Great job! You currently have no topics marked as Weak.');
      } else {
        stats.weakTopics.forEach((t, idx) => {
          doc.text(`${idx + 1}. ${t.name} (Subject: ${t.subjectName})`);
        });
      }

      doc.moveDown(2);
      doc.fillColor('#718096').fontSize(8).text('Generated by OpenPrep AI Learning Platform', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

const sendWeeklyDigests = async () => {
  console.log('[CRON] Starting weekly digests job...');
  const users = await User.findAll({ where: { receiveWeeklyDigest: true } });
  
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

  for (const user of users) {
    try {
      // 1. Calculate weekly study hours from ActivityLog
      const logs = await ActivityLog.findAll({
        where: {
          user: user.id,
          createdAt: { [Op.gte]: sevenDaysAgo },
        },
        raw: true,
      });

      let weeklyHours = 0;
      for (const log of logs) {
        const match = log.description.match(/Studied for ([\d.]+) hour/i);
        if (match) {
          weeklyHours += parseFloat(match[1]);
        }
      }

      // 2. Count completed topics this week (updated in last 7 days with 100% completion)
      const completedProgress = await Progress.findAll({
        where: {
          user: user.id,
          completionPercentage: 100,
          updatedAt: { [Op.gte]: sevenDaysAgo },
          topic: { [Op.ne]: null },
        },
        raw: true,
      });
      const completedTopicsCount = completedProgress.length;

      // 3. Find weak topics
      const weakTopicsRaw = await Topic.findAll({
        where: {
          user: user.id,
          status: 'Weak',
        },
        raw: true,
      });

      // Find subjects to resolve subject names
      const subjects = await Subject.findAll({
        where: { user: user.id },
        raw: true,
      });
      const subjectMap = {};
      subjects.forEach((s) => {
        subjectMap[s.id] = s.name;
      });

      const weakTopics = weakTopicsRaw.map((t) => ({
        name: t.name,
        subjectName: subjectMap[t.subject] || 'N/A',
      }));

      // 4. Calculate subject-wise stats (topics and hours)
      const progressRecords = await Progress.findAll({
        where: { user: user.id },
        raw: true,
      });

      const subjectStatsMap = {};
      progressRecords.forEach((p) => {
        if (!subjectStatsMap[p.subject]) {
          subjectStatsMap[p.subject] = { name: subjectMap[p.subject] || 'N/A', topicsCount: 0, hours: 0 };
        }
        if (p.topic) {
          subjectStatsMap[p.subject].topicsCount += 1;
        }
        subjectStatsMap[p.subject].hours += p.studyHours || 0;
      });

      const subjectStats = Object.values(subjectStatsMap);

      const stats = {
        weeklyHours,
        completedTopicsCount,
        weakTopics,
        subjectStats,
      };

      // 5. Generate PDF attachment
      const pdfBuffer = await generateWeeklyPDFBuffer(user, stats);

      // 6. Build HTML email body
      const htmlBody = `
        <div style="font-family: 'Georgia', serif; background-color: #fdfaf3; padding: 30px; border: 1px solid #d4af37; max-width: 600px; margin: 0 auto; color: #2d3748;">
          <h2 style="color: #c5a059; border-bottom: 2px solid #c5a059; padding-bottom: 10px; font-weight: normal; font-family: 'Playfair Display', serif;">
            Weekly Mastery Summary
          </h2>
          <p>Dear <strong>${user.name}</strong>,</p>
          <p>Congratulations on another week of preparation. Here is a summary of your performance over the last 7 days:</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr style="background-color: #f7f4eb;">
              <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Study Hours Logged</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right;">${weeklyHours.toFixed(1)} hours</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Completed Topics</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right;">${completedTopicsCount}</td>
            </tr>
            <tr style="background-color: #f7f4eb;">
              <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Current Streak</td>
              <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right;">${user.streakCount || 0} days</td>
            </tr>
          </table>

          <p>Please find attached your detailed <strong>Mastery Analytics PDF Report</strong>, which outlines subject mastery levels and highlights areas requiring focus (your weak topics).</p>
          
          <p style="margin-top: 30px; font-style: italic; font-size: 13px; color: #718096; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            To opt-out of these weekly emails, you can update your notification settings in your user profile inside OpenPrep AI.
          </p>
          <p style="color: #c5a059; font-weight: bold; margin-top: 20px;">Keep going,<br/>The OpenPrep AI Team</p>
        </div>
      `;

      await sendEmail({
        to: user.email,
        subject: 'Weekly Study Digest — OpenPrep AI',
        text: `Hello ${user.name},\n\nHere is your study summary for this week:\n- Study Hours Logged: ${weeklyHours.toFixed(1)}\n- Completed Topics: ${completedTopicsCount}\n- Current Streak: ${user.streakCount || 0} days.\n\nPlease find your detailed Mastery Analytics PDF attached.\n\nKeep studying!\nThe OpenPrep AI Team`,
        html: htmlBody,
        attachments: [
          {
            filename: `mastery_analytics_${new Date().toISOString().split('T')[0]}.pdf`,
            content: pdfBuffer,
            contentType: 'application/pdf',
          },
        ],
      });
      console.log(`[CRON] Digest email sent successfully to ${user.email}`);
    } catch (err) {
      console.error(`[CRON] Failed to send digest for user ${user.email}:`, err);
    }
  }
};

// Schedule job: every Sunday at 00:00
const startScheduler = () => {
  cron.schedule('0 0 * * 0', async () => {
    await sendWeeklyDigests();
  });
  console.log('[CRON] Weekly digest scheduler initialized.');
};

module.exports = {
  sendWeeklyDigests,
  startScheduler,
};
