-- Add OCR fields to Notes table
ALTER TABLE "Notes" ADD COLUMN IF NOT EXISTS "isOcrExtracted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Notes" ADD COLUMN IF NOT EXISTS "ocrConfidence" FLOAT NULL;
ALTER TABLE "Notes" ADD COLUMN IF NOT EXISTS "originalImageUrl" VARCHAR(255) NULL;
