version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    restart: always
    environment:
      - NODE_ENV=production
    volumes: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - '80:80'
    volumes: []
