import React, { useMemo } from 'react';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkMath from 'remark-math';
import remarkRehype from 'remark-rehype';
import rehypeKatex from 'rehype-katex';
import rehypeStringify from 'rehype-stringify';
import DOMPurify from 'dompurify';
import 'katex/dist/contrib/mhchem.mjs';
import 'katex/dist/katex.min.css';

/**
 * Shared unified processor: Markdown -> Math -> HTML string.
 * Built once at module scope so repeated renders reuse the pipeline.
 * `throwOnError: false` makes KaTeX render malformed LaTeX inline with a
 * `.katex-error` indicator instead of throwing and breaking the tree.
 */
const processor = unified()
  .use(remarkParse)
  .use(remarkMath)
  .use(remarkRehype)
  .use(rehypeKatex, { throwOnError: false, strict: false })
  .use(rehypeStringify);

/**
 * MathML elements generated by KaTeX (for screen-reader accessibility).
 * DOMPurify strips unknown tags by default, so these must be allow-listed
 * or the `<math>` accessibility layer would be removed from the output.
 */
const MATHML_TAGS = [
  'math', 'semantics', 'mrow', 'mi', 'mo', 'mn', 'msup', 'msub', 'msubsup',
  'mfrac', 'msqrt', 'mroot', 'mspace', 'mtext', 'mstyle', 'mtable', 'mtr',
  'mtd', 'munder', 'mover', 'munderover', 'mphantom', 'mpadded', 'annotation',
  'menclose', 'merror', 'mfenced', 'mglyph', 'mlongdiv', 'mmultiscripts',
  'none', 'mlabeledtr', 'mprescripts',
];

const MATHML_ATTRS = [
  'xmlns', 'encoding', 'mathvariant', 'stretchy', 'separator', 'lspace',
  'rspace', 'fence', 'form', 'largeop', 'movablelimits', 'symmetric', 'index',
  'scriptlevel', 'displaystyle', 'accent', 'accentunder', 'align',
  'columnalign', 'rowalign', 'columnspacing', 'rowspacing', 'columnlines',
  'rowlines', 'frame', 'framespacing', 'equalcolumns', 'equalrows', 'side',
  'minlabelspacing', 'voffset', 'width', 'height', 'depth', 'linethickness',
  'rowspan', 'columnspan', 'bevelled', 'notation', 'mathbackground',
  'mathcolor', 'mathsize', 'open', 'close', 'separators',
];

/** Sanitize generated HTML while preserving KaTeX MathML for a11y. */
const sanitizeMathHtml = (html) =>
  DOMPurify.sanitize(html, {
    USE_PROFILES: { html: true },
    ADD_TAGS: MATHML_TAGS,
    ADD_ATTR: MATHML_ATTRS,
  });

/**
 * MathRenderer: Renders Markdown text containing inline ($...$) and block
 * ($$...$$) LaTeX math plus mhchem chemical formulas (\ce{...}) using KaTeX.
 *
 * - remark-math / rehype-katex handle the math parsing and rendering.
 * - katex/contrib/mhchem registers \ce and \pu for chemical equations.
 * - DOMPurify sanitizes the generated HTML to prevent XSS from raw HTML tags.
 * - React.memo + useMemo avoid re-parsing static strings on re-render.
 */
const MathRenderer = ({ text = '', className = '' }) => {
  const html = useMemo(() => {
    if (typeof text !== 'string' || !text) return '';
    try {
      const raw = processor.processSync(text).toString();
      return sanitizeMathHtml(raw);
    } catch (err) {
      console.error('MathRenderer error:', err);
      return `<code class="math-renderer-error">${text}</code>`;
    }
  }, [text]);

  if (!html) return null;

  return (
    <span
      className={`math-renderer inline ${className}`}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
};

export default React.memo(MathRenderer);